---

- name: dracut | packages
  tags:
  - package
  package:
    name: 
    - intel-microcode
    - dracut-network

- name: dracut | config
  tags:
  - config
  template:
    src: dracut.conf.j2
    dest: "{{ dracut_conf_path }}"

- name: dracut | update-dracut.sh tool
  copy:
    src: update-dracut.sh
    dest: /usr/local/bin/
    mode: '0755'

- name: dracut | dirs for extra includes
  tags:
  - dirs
  file:
    path: "{{ dracut_extra_dir }}/{{ item }}"
    state: directory
  loop: "{{ dracut_extra | list | map('dirname') }}"

- name: dracut | extra includes
  copy:
    content: "{{ item.value }}"
    dest: "{{ dracut_extra_dir }}/{{ item.key }}"
  loop: "{{ dracut_extra | dict2items }}"
