#! /usr/bin/env ansible-playbook
# Configure dracut role
# Replace 'dracut' with your own inventory group
---
- name: dracut | create initramfs
  hosts: dracut
  roles:
  - role: dracut
    tags:
    - dracut
