#! /usr/bin/env ansible-playbook
# Uninstall role
# Run prior to removing host from inventory groups, so hostvars are accessible
---
- name: dracut | uninstall
  hosts: dracut
  tasks:
  - include_role:
      name: dracut
      tasks_from: uninstall.yml
